#if !canImport(ObjectiveC)
import XCTest

extension XMLRPCTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__XMLRPCTests = [
        ("testRequest", testRequest),
        ("testResponse", testResponse),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(XMLRPCTests.__allTests__XMLRPCTests),
    ]
}
#endif
